namespace = Healthbar

[Present]
if !$\zHealthbar\active && ($character_id_0 != 0 && $character_id_1 != 0 && $character_id_2 != 0)
	post run = CommandList.Reset
endif

[CommandListRequestUpdate]
$\zHealthbar\update_request = 3

[Constants]
global $character_id = 0

global $current_id = 0
global $current_value = 0

global $character_id_0 = 0
global $character_id_1 = 0
global $character_id_2 = 0

global $Alice = 1
global $Anby = 1
global $Anby0 = 1
global $Soldier0Anby = 1
global $Anton = 1
global $Yutane = 1
global $Aria = 1
global $Astra = 1
global $AstraYao = 1
global $Banyue = 1
global $Ben = 1
global $Billy = 1
global $Burnice = 1
global $Caesar = 1
global $Corin = 1
global $Dialyn = 1
global $Ellen = 1
global $Evelyn = 1
global $Grace = 1
global $Harumasa = 1
global $AsabaHarumasa = 1
global $Hugo = 1
global $Jane = 1
global $JaneDoe = 1
global $JuFufu = 1
global $Koleda = 1
global $Lighter = 1
global $Lucia = 1
global $Lucy = 1
global $Lycaon = 1
global $Manato = 1
global $Miyabi = 1
global $HoshimiMiyabi = 1
global $Nekomata = 1
global $Nicole = 1
global $Orphie = 1
global $Pan = 1
global $PanYinhu = 1
global $Piper = 1
global $Pulchra = 1
global $Qingyi = 1
global $Rina = 1
global $Seth = 1
global $Seed = 1
global $Soldier11 = 1
global $Soukaku = 1
global $Chinatsu = 1
global $Sunna = 1
global $Trigger = 1
global $Vivian = 1
global $Yanagi = 1
global $TsukishiroYanagi = 1
global $YeShunguang = 1
global $Yidhari = 1
global $Yixuan = 1
global $Yuzuha = 1
global $Zhao = 1
global $ZhuYuan = 1
global $Rokudo = 1
global $Nangong = 1
global $NangongYu = 1



[TextureOverride Alice]
match_priority = -9999
hash = 93ef2127
$character_id = 1

[TextureOverride Alice Skin]
match_priority = -9999
hash = e65f485b
$character_id = 1

[TextureOverride Anby]
match_priority = -9999
hash = fcc6b33f
$character_id = 2

[TextureOverride Soldier0Anby]
match_priority = -9999
hash = 5b73ab49
$character_id = 3

[TextureOverride Anton]
match_priority = -9999
hash = 3ca717ef
$character_id = 4

[TextureOverride Aria]
match_priority = -9999
hash = 6b425446
$character_id = 5

[TextureOverride Aria Skin]
match_priority = -9999
hash = 540da02f
$character_id = 5

[TextureOverride AstraYao]
match_priority = -9999
hash = df13c5de
$character_id = 6

[TextureOverride AstraYao Skin]
match_priority = -9999
hash = 1ed7d804
$character_id = 6

[TextureOverride Banyue]
match_priority = -9999
hash = 37024446
$character_id = 7

[TextureOverride Ben]
match_priority = -9999
hash = a611b261
$character_id = 8

[TextureOverride Billy]
match_priority = -9999
hash = de11fb92
$character_id = 9

[TextureOverride Burnice]
match_priority = -9999
hash = ef514533
$character_id = 10

[TextureOverride Caesar]
match_priority = -9999
hash = d3e117bb
$character_id = 11

[TextureOverride Corin]
match_priority = -9999
hash = 1f4fea0b
$character_id = 12

[TextureOverride Dialyn]
match_priority = -9999
hash = 96c4e0ac
$character_id = 13

[TextureOverride Ellen]
match_priority = -9999
hash = 6c54850d
$character_id = 14

[TextureOverrided Ellen Skin]
match_priority = -9999
hash = a5c30495
$character_id = 14

[TextureOverride Evelyn]
match_priority = -9999
hash = 579a4b03
$character_id = 15

[TextureOverride Grace]
match_priority = -9999
hash = 0671beba
$character_id = 16

[TextureOverride AsabaHarumasa]
match_priority = -9999
hash = dea2ec24
$character_id = 17

[TextureOverride Hugo]
match_priority = -9999
hash = 8d1e4119
$character_id = 18

[TextureOverride JaneDoe]
match_priority = -9999
hash = cbe98417
$character_id = 19

[TextureOverride JaneDoe Skin]
match_priority = -9999
hash = b44ac3ee
$character_id = 19

[TextureOverride JuFufu]
match_priority = -9999
hash = 4c40d3aa
$character_id = 20

[TextureOverride Koleda]
match_priority = -9999
hash = e9146789
$character_id = 21

[TextureOverride Lighter]
match_priority = -9999
hash = a302421d
$character_id = 22

[TextureOverride Lucia]
match_priority = -9999
hash = 8ef7845d
$character_id = 23

[TextureOverride Lucy]
match_priority = -9999
hash = 66494aea
$character_id = 24

[TextureOverride Lycaon]
match_priority = -9999
hash = 4f0296bc
$character_id = 25

[TextureOverride Manato]
match_priority = -9999
hash = 9ac8ed71
$character_id = 26

[TextureOverride Manato Skin]
match_priority = -9999
hash = ae9eee53
$character_id = 26

[TextureOverride HoshimiMiyabi]
match_priority = -9999
hash = 70d8c49c
$character_id = 27

[TextureOverride Nekomata]
match_priority = -9999
hash = 273ec328
$character_id = 28

[TextureOverride Nicole]
match_priority = -9999
hash = 76b8d2f3
$character_id = 29

[TextureOverride Nicole Skin]
match_priority = -9999
hash = a39a4c20
$character_id = 29

[TextureOverride Orphie]
match_priority = -9999
hash = 19ccda9d
$character_id = 30

[TextureOverride PanYinhu]
match_priority = -9999
hash = 46795a4a
$character_id = 31

[TextureOverride PanYinhu Skin]
match_priority = -9999
hash = e2fe2a89
$character_id = 31

[TextureOverride Piper]
match_priority = -9999
hash = 5aef8344
$character_id = 32

[TextureOverride Pulchra]
match_priority = -9999
hash = a1c3c4ac
$character_id = 33

[TextureOverride Qingyi]
match_priority = -9999
hash = 6a4daa3a
$character_id = 34

[TextureOverride Rina]
match_priority = -9999
hash = c9a1ebb6
$character_id = 35

[TextureOverride Seth]
match_priority = -9999
hash = 870cd37c
$character_id = 36

[TextureOverride Seed]
match_priority = -9999
hash = 5088013d
$character_id = 37

[TextureOverride Soldier11]
match_priority = -9999
hash = 728f0f41
$character_id = 38

[TextureOverride Soukaku]
match_priority = -9999
hash = fcc2aca0
$character_id = 39

[TextureOverride Sunna]
match_priority = -9999
hash = d90b8fb8
$character_id = 40

[TextureOverride Sunna Skin]
match_priority = -9999
hash = b338a781
$character_id = 40

[TextureOverride Trigger]
match_priority = -9999
hash = 7d4b7bd0
$character_id = 41

[TextureOverride Vivian]
match_priority = -9999
hash = c4c45127
$character_id = 42

[TextureOverride Vivian Skin]
match_priority = -9999
hash = 84e06de0
$character_id = 42

[TextureOverride TsukishiroYanagi]
match_priority = -9999
hash = 7d098af3
$character_id = 43

[TextureOverride YeShunguang]
match_priority = -9999
hash = 8a4c7132
$character_id = 44

[TextureOverride YeShunguang Skin]
match_priority = -9999
hash = 64f20e30
$character_id = 44

[TextureOverride Yidhari]
match_priority = -9999
hash = 76d31c13
$character_id = 45

[TextureOverride Yixuan]
match_priority = -9999
hash = e8b15d3f
$character_id = 46

[TextureOverride Yixuan Skin]
match_priority = -9999
hash = 0fa88007
$character_id = 46

[TextureOverride Yuzuha]
match_priority = -9999
hash = 8c042e95
$character_id = 47

[TextureOverride Yuzuha Skin]
match_priority = -9999
hash = a4340446
$character_id = 47

[TextureOverride Zhao]
match_priority = -9999
hash = f8d54341
$character_id = 48

[TextureOverride ZhuYuan]
match_priority = -9999
hash = 01ef757f
$character_id = 49

[TextureOverride NangongYu]
match_priority = -9999
hash = f19b08bb
$character_id = 50
[TextureOverride NangongYu Skin]
match_priority = -9999
hash = b34e9d55
$character_id = 50


[CommandListSetValue]
if $current_id == 0
elif $current_id < 26
	if $current_id < 13
		if $current_id < 7
			if $current_id < 4
				if $current_id < 2
					$Alice = $current_value
				elif $current_id == 2
					$Anby = $current_value
				else
					$Anby0 = $current_value
					$Soldier0Anby = $current_value
				endif
			elif $current_id == 4
				$Anton = $current_value
			else
				if $current_id == 5
					$Yutane = $current_value
					$Aria = $current_value
				else
					$Astra = $current_value
					$AstraYao = $current_value
				endif
			endif
		elif $current_id == 7
			$Banyue = $current_value
		else
			if $current_id < 10
				if $current_id == 8
					$Ben = $current_value
				else
					$Billy = $current_value
				endif
			elif $current_id == 10
				$Burnice = $current_value
			else
				if $current_id == 11
					$Caesar = $current_value
				else
					$Corin = $current_value
				endif
			endif
		endif
	elif $current_id == 13
		$Dialyn = $current_value
	else
		if $current_id < 20
			if $current_id < 17
				if $current_id < 15
					$Ellen = $current_value
				elif $current_id == 15
					$Evelyn = $current_value
				else
					$Grace = $current_value
				endif
			elif $current_id == 17
				$Harumasa = $current_value
				$AsabaHarumasa = $current_value
			else
				if $current_id == 18
					$Hugo = $current_value
				else
					$Jane = $current_value
					$JaneDoe = $current_value
				endif
			endif
		elif $current_id == 20
			$JuFufu = $current_value
		else
			if $current_id < 23
				if $current_id == 21
					$Koleda = $current_value
				else
					$Lighter = $current_value
				endif
			elif $current_id == 23
				$Lucia = $current_value
			else
				if $current_id == 24
					$Lucy = $current_value
				else
					$Lycaon = $current_value
				endif
			endif
		endif
	endif
elif $current_id == 26
	$Manato = $current_value
else
	if $current_id < 39
		if $current_id < 33
			if $current_id < 30
				if $current_id < 28
					$Miyabi = $current_value
					$HoshimiMiyabi = $current_value
				elif $current_id == 28
					$Nekomata = $current_value
				else
					$Nicole = $current_value
				endif
			elif $current_id == 30
				$Orphie = $current_value
			else
				if $current_id == 31
					$Pan = $current_value
					$PanYinhu = $current_value
				else
					$Piper = $current_value
				endif
			endif
		elif $current_id == 33
			$Pulchra = $current_value
		else
			if $current_id < 36
				if $current_id == 34
					$Qingyi = $current_value
				else
					$Rina = $current_value
				endif
			elif $current_id == 36
				$Seth = $current_value
			else
				if $current_id == 37
					$Seed = $current_value
				else
					$Soldier11 = $current_value
				endif
			endif
		endif
	elif $current_id == 39
		$Soukaku = $current_value
	else
		if $current_id < 45
			if $current_id < 42
				if $current_id == 40
					$Chinatsu = $current_value
					$Sunna = $current_value
				else
					$Trigger = $current_value
				endif
			elif $current_id == 42
				$Vivian = $current_value
			else
				if $current_id == 43
					$Yanagi = $current_value
					$TsukishiroYanagi = $current_value
				else
					$YeShunguang = $current_value
				endif
			endif
		elif $current_id == 45
			$Yidhari = $current_value
		else
			if $current_id < 48
				if $current_id == 46
					$Yixuan = $current_value
				else
					$Yuzuha = $current_value
				endif
			elif $current_id == 48
				$Zhao = $current_value
			else
				if $current_id == 49
					$ZhuYuan = $current_value
				else
					$Rokudo = $current_value
					$Nangong = $current_value
					$NangongYu = $current_value
				endif
			endif
		endif
	endif
endif



[CommandList.Reset]
$character_id = 0
$current_id = 0
$current_value = 0

;$value_0 = -1
$character_id_0 = 0
;$value_1 = -1
$character_id_1 = 0
;$value_2 = -1
$character_id_2 = 0

$Alice = 1
$Anby = 1
$Anby0 = 1
$Soldier0Anby = 1
$Anton = 1
$Aria = 1
$Astra = 1
$AstraYao = 1
$Banyue = 1
$Ben = 1
$Billy = 1
$Burnice = 1
$Caesar = 1
$Corin = 1
$Dialyn = 1
$Ellen = 1
$Evelyn = 1
$Grace = 1
$Harumasa = 1
$AsabaHarumasa = 1
$Hugo = 1
$Jane = 1
$JaneDoe = 1
$JuFufu = 1
$Koleda = 1
$Lighter = 1
$Lucia = 1
$Lucy = 1
$Lycaon = 1
$Manato = 1
$Miyabi = 1
$HoshimiMiyabi = 1
$Nekomata = 1
$Nicole = 1
$Orphie = 1
$Pan = 1
$PanYinhu = 1
$Piper = 1
$Pulchra = 1
$Qingyi = 1
$Rina = 1
$Seth = 1
$Seed = 1
$Soldier11 = 1
$Soukaku = 1
$Sunna = 1
$Trigger = 1
$Vivian = 1
$Yanagi = 1
$TsukishiroYanagi = 1
$YeShunguang = 1
$Yidhari = 1
$Yixuan = 1
$Yuzuha = 1
$Zhao = 1
$ZhuYuan = 1
