namespace = zHealthbar

[Constants]
global $active = 0

global $character_counter = 0
global $teammates_counter = 0
global $hp_counter = 0
global $icon_counter = 0
global $store_temp = -1

global $hp_main = -1
global $hp_team_1 = -1
global $hp_team_2 = -1

global $next_update = 0
global $update_request = 0

[Present]
if $character_counter && $hp_main == -1
	pre run = CommandList.SetValue
endif
post run = CommandList.Clear

[CommandList.Clear]
if $active
	$hp_counter = 0
	$active = $active - 1
	$teammates_counter = 0
	if $update_request
		$update_request = $update_request - 1
	endif
	if $icon_counter
		$character_counter = $icon_counter
		$icon_counter = 0
	endif
	if $hp_main != -1 && (time > $next_update)
		clear = Resource.UAV
		
		$hp_main = -1
		$hp_team_1 = -1
		$hp_team_2 = -1

		$next_update = time + 0.35
	endif
elif $character_counter
	$character_counter = 0
endif


[ShaderOverridez UI Icons VS]
hash = cdc90aee00e7900d
allow_duplicate_hash = true
filter_index = 909.709
if $active && !$\Healthbar\character_id
	if ps == 857.625 && $\ZZMIv1\check_textures != 2
		CheckTextureOverride = ps-t0
	endif
endif
[ShaderOverridez UI Icons PS]
hash = 857cd16250c6142e
allow_duplicate_hash = true
filter_index = 857.625
if $active && $\Healthbar\character_id
	if vs == 909.709
		$icon_counter = $icon_counter + 1
		if $update_request && $hp_main == -1
			run = CustomShader.OrderIds
		endif
	endif
	$\Healthbar\character_id = 0
endif


[CommandList.SetValue]
store = $store_temp, ref Resource.UAV, 7
;$hp_main = (($store_temp // (101**2)) % 101) / 100
$hp_main = (($store_temp // 10201) % 101) / 100
$hp_team_1 = (($store_temp // 101) % 101) / 100
$hp_team_2 = ($store_temp % 101) / 100

store = $store_temp, ref Resource.UAV, 15
$\Healthbar\character_id_0 = (($store_temp // 2601) % 51) // 1
$\Healthbar\character_id_1 = (($store_temp // 51) % 51) // 1
$\Healthbar\character_id_2 = ($store_temp % 51) // 1

$\Healthbar\current_id = $\Healthbar\character_id_0
$\Healthbar\current_value = $hp_main
run = CommandList\Healthbar\SetValue

$\Healthbar\current_id = $\Healthbar\character_id_1
$\Healthbar\current_value = $hp_team_1
run = CommandList\Healthbar\SetValue

$\Healthbar\current_id = $\Healthbar\character_id_2
$\Healthbar\current_value = $hp_team_2
run = CommandList\Healthbar\SetValue

[Resource.UAV]
type = StructuredBuffer
array = 1
; hp		0,1,2
; hp_pos	0,1,2
; hp_acc	hp_counter, hp_summ

; id		0,1,2
; id_pos	0,1,2
; id_acc	id_counter, id_summ
data = R32_FLOAT  0 0 0  0 0 0  0 0   0 0 0  0 0 0  0 0

[CustomShader.OrderIds]
flags = optimization_level3 all_resources_bound partial_precision skip_validation
cs = OrderIds.CS.hlsl

local $x1 = x1
local $y1 = y1
local $z1 = z1

x1 = first_vertex // 2
y1 = $\Healthbar\character_id // 1
z1 = $character_counter // 1

cs-u0 = ref Resource.UAV
cs-t0 = vb0
Dispatch = 1, 1, 1

x1 = $x1
y1 = $y1
z1 = $z1

[CustomShader.SummHp]
flags = optimization_level3 all_resources_bound partial_precision skip_validation
cs = SummHp.CS.hlsl

local $x1 = x1
local $y1 = y1

x1 = first_vertex // 2
y1 = $character_counter // 1

cs-u0 = ref Resource.UAV
cs-t0 = ps-cb0
cs-t1 = vb0
Dispatch = 1, 1, 1

x1 = $x1
y1 = $y1

[ShaderOverridez UI Hp bar VS]
hash = 0086a8159f4d9a00
allow_duplicate_hash = true
filter_index = 8681.5949
[ShaderOverridez UI Hp bar PS]
hash = dce9c76d7f184caf
if $costume_mods && (index_count == 6 || index_count == 54)
	if vs == 8681.5949 && ps-t0 == 1024.999
		$active = 3
		if $character_counter > $icon_counter
			if $update_request && $hp_main == -1
				run = CustomShader.SummHp
			endif
		endif
	endif
endif

[TextureOverridez UI atlas]
match_type = Texture2D
match_format = BC3_UNORM_SRGB
match_width = 1024
match_height = 1024
match_mips = 1
match_priority = 999
filter_index = 1024.999
