namespace = SlotFix\Matches


[Constants]
global $slot = 0
global $match = 0


[CommandListMatch]
; $match = $PoolCache[@Pool\SlotFix\t[$slot]]
; if !$match
; 	run = CommandList.Run
; 	$PoolCache[@Pool\SlotFix\t[$slot]] = $match
; endif
$match = 0
run = CommandList.Run
$Pool\SlotFix\t[$slot] = $match

[CommandList.Run]
local $format = Pool\SlotFix\t[$slot]->Format
local $width = Pool\SlotFix\t[$slot]->Width
local $height = Pool\SlotFix\t[$slot]->Height
local $mips = Pool\SlotFix\t[$slot]->Mips

if $mips == 1 && ($format == DXGI_FORMAT_R16_TYPELESS || $format == DXGI_FORMAT_R16_UNORM || $format == DXGI_FORMAT_R16_FLOAT)
	; R16_TYPELESS depth_stencil
	$match = 5353.1

elif $width == 1024 && $height == 32 && $mips == 1 && ($format == DXGI_FORMAT_R16G16B16A16_TYPELESS || $format == DXGI_FORMAT_R16G16B16A16_FLOAT || $format == DXGI_FORMAT_R16G16B16A16_UNORM)
	; LuT
	$match = 5353.2

elif $width == $height
	if $format == DXGI_FORMAT_BC7_UNORM_SRGB
		; Diffuse: >255, mips >8
		; Glow gradient1/2, Nagi Censor Ex Effect 3: 256 / 128 / 512, mips 1
		; Nagi Censor Ex Effect (+low): 128 mips 8, 64 mips 7
		if ($height >= 256 && $mips >= 9 && $height <= 2048) || ($mips == 1 && ($height == 128 || $height == 256 || $height == 512)) || ($height == 128 && $mips == 8) || ($height == 64 && $mips == 7)
			$match = 3535.003
		; NPC maps (+low): 32 mips 6, 16 mips 5
		elif ($height == 32 && $mips == 6) || ($height == 16 && $mips == 5)
			$match = 3535.305
		endif

	elif $format == DXGI_FORMAT_BC7_UNORM
		; Char LM && MM, Room Object NM: >63, mips >6
		if $height >= 64 && $mips >= 7
			$match = 3535.006
		; Boo maps (+low): 32 mips 6, 16 mips 5
		elif ($height == 32 && $mips == 6) || ($height == 16 && $mips == 5)
			$match = 3535.205
		; PurpleGreen map: 256, mips 1
		elif $height == 256 && $mips == 1
			$match = 5353.3
		endif

	elif $format == DXGI_FORMAT_R8G8B8A8_UNORM
		; NormalMap: >127, mips >7
		if $height >= 128 && $mips >= 8
			$match = 3535.004
		endif

	elif $format == DXGI_FORMAT_BC6H_UF16
		; Char LM: >255, mips >8
		if $height >= 256 && $mips >= 9
			$match = 3535.005
		; NPC LM/MM (+low): 32 mips 6, 16 mips 5
		elif ($height == 32 && $mips == 6) || ($height == 16 && $mips == 5)
			$match = 3535.306
		endif

	elif $format == DXGI_FORMAT_BC1_UNORM_SRGB
		; some Glow map: >255, mips 1
		; Room Object Diffuse: >63, mips >6
		if ($height >= 256 && $mips == 1) || ($height >= 64 && $mips >= 7)
			$match = 3535.102
		endif

	elif $format == DXGI_FORMAT_BC3_UNORM_SRGB
		; Room Object Diffuse2: >255, mips >8
		if $height >= 256 && $mips >= 9
			$match = 3535.102
		endif

	elif $format == DXGI_FORMAT_BC1_UNORM
		; Room Object LM: >63, mips >6
		if $height >= 64 && $mips >= 7
			$match = 3535.104
		endif

	elif $format == DXGI_FORMAT_R16G16B16A16_FLOAT
		; Char Face NM (+low): 256 mips 9, 128 mips 8
		if ($height == 256 && $mips == 9) || ($height == 128 && $mips == 8)
			$match = 5353.04
		endif

	elif $format == DXGI_FORMAT_R8G8B8A8_UNORM_SRGB
		; Magic square: 4
		if $height == 4
			$match = 5353.0
		endif
	endif
endif


[PoolCache]
pool_size = 666
pool_index_type = fifo
pool_variable_default_value = 0


[TextureOverride NormalMap]
match_type = Texture2D
match_format = R8G8B8A8_UNORM
match_width = height
match_height = >127
match_mips = >7

this = Resource\ZZMI\FlatNormalMap
