namespace = ZZMI

[Constants]
global $sk_deltas_count = -1
global $shapekey_count = -1
global $_format = 0
global $sk_index = -1
global $sk_value = 0.0
global $null_multipliers = 0

; Shape Keys Override -------------------------

[ShaderOverrideShapeKeyLoaderCS_ZZZ]
hash = 743108cc03f39cbf
allow_duplicate_hash = true
if $costume_mods
	checktextureoverride = cs-t0
endif

[ShaderOverrideShapeKeyLoaderCS_HSR]
hash = 893b6d8f0a84ca0d
allow_duplicate_hash = true
if $costume_mods
	checktextureoverride = cs-t0
endif

; Command Lists ------------------------------

[CommandListGatherSKData]
if $costume_mods && (ResourceSKIdentity !== null && ResourceSKMultipliers !== null)
	handling = skip
	cs-t100 = ref ResourceSKIdentity
	cs-u7 = ref ResourceSKMultipliers
	run = CustomShaderSKDataGather
	ResourceSKIdentity = null
	ResourceSKMultipliers = null
endif

[CommandListResetData]
$sk_index = -1
$sk_value = 0.0
$sk_deltas_count = -1
$_format = 0
$null_multipliers = 0
ResourceSKBase = null
ResourceSKDeltas = null
ResourceSKIdentity = null
ResourceSKOverrides = null
ResourceSKMultipliers = null

; Custom Shaders -----------------------------

[CustomShaderSKDataGather]
cs = Shaders/ShapeKeyDataGather.hlsl
; Input:
; cs-t100 = ogoffset, ogcount, newoffset, newcount
; vanilla cs-cb0 = offset, count, multiplier, unused
; cs-u7 = multipliers
;
; Output:
; cs-u7 Updates the multiplier for the given SK that attempted to be applied and 
; skips the vanilla application in favor of modded application later
dispatch = 1, 1, 1
cs-t100 = null
cs-u7 = null
; TODO: NEEDS VARIANTION FOR STRIDES AND POSITION FORMATS

[CommandListApplyShapekeys]
cs-u7 = ref ResourceSKBase
cs-t100 = ref ResourceSKDeltas
cs-t101 = ref ResourceSKIdentity
if !$null_multipliers
	cs-t102 = ref ResourceSKMultipliers
endif
cs-t103 = ref ResourceSKOverrides

if $_format == 0
	; Position: Float3
	; Normal: float3
	; Tangent: float4
	run = CustomShaderApplyShapekeys
endif
clear = ResourceSKMultipliers
run = CommandListResetData

[CustomShaderApplyShapekeys]
cs = Shaders/ShapeKeyApply.hlsl
; Output:
; cs-u7 = Modified Mesh position
if $sk_deltas_count > 0
	dispatch = ($sk_deltas_count + 63) // 64, 1, 1
endif
cs-t100 = null
cs-t101 = null
cs-t102 = null
cs-t103 = null
cs-u7 = null

[CommandListSetShapeKeyValue]
run = CustomShaderSetShapeKeyValue
run = CommandListResetData

[CustomShaderSetShapeKeyValue]
cs = Shaders/ShapeKeySetValue.hlsl
local $bak_0x = x0
local $bak_0y = y0
x0 = $sk_index
y0 = $sk_value
cs-u7 = ref ResourceSKOverrides
dispatch = 1, 1, 1
x0 = $bak_0x
y0 = $bak_0y

; Resources ----------------------------------

[ResourceSKBase]

[ResourceSKDeltas]

[ResourceSKIdentity]

[ResourceSKMultipliers]

[ResourceSKOverrides]
